//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCommand.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostavkiTovarEntities : DbContext
    {
        public PostavkiTovarEntities()
            : base("name=PostavkiTovarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<D> D { get; set; }
        public virtual DbSet<S> S { get; set; }
        public virtual DbSet<STD> STD { get; set; }
        public virtual DbSet<STD_Temp> STD_Temp { get; set; }
        public virtual DbSet<T> T { get; set; }
        public virtual DbSet<Tovar_Temp> Tovar_Temp { get; set; }
    }
}
