//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCommand.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STD
    {
        public string Snum { get; set; }
        public string Tnum { get; set; }
        public string Dnum { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public string DatePost { get; set; }
    
        public virtual D D { get; set; }
        public virtual S S { get; set; }
        public virtual T T { get; set; }
    }
}
