//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCommand.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_Temp
    {
        public string Tnum { get; set; }
        public string Tname { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string EdIzm { get; set; }
        public string City { get; set; }
    }
}
